# fly.toml app configuration file generated for tel-solvia on 2025-01-06T16:00:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tel-solvia'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'no'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
